# This wraps PyPostNote into an executable file.

$arguments = 'main.py',
             '-w',
             '--noconfirm',
			 '--clean',
			 '--name',
			 'pypostnote',
			 '--icon',
			 'Resources/PostNote.ico',
			 '--add-binary',
			 'Resources/Bold.png;Resources',
			 '--add-binary',
			 'Resources/Bullet Table.png;Resources',
			 '--add-binary',
			 'Resources/Center.png;Resources',
			 '--add-binary',
			 'Resources/eye.png;Resources',
			 '--add-binary',
			 'Resources/Horiz Line.png;Resources',
			 '--add-binary',
			 'Resources/Italic.png;Resources',
			 '--add-binary',
			 'Resources/Left.png;Resources',
			 '--add-binary',
			 'Resources/No Color.png;Resources',
			 '--add-binary',
			 'Resources/Number Table.png;Resources',
			 '--add-binary',
			 'Resources/properties.png;Resources',
			 '--add-binary',
			 'Resources/Right.png;Resources',
			 '--add-binary',
			 'Resources/Table.png;Resources',
			 '--add-binary',
			 'Resources/Text Background.png;Resources',
			 '--add-binary',
			 'Resources/Text Foreground.png;Resources',
			 '--add-binary',
			 'Resources/trash-can.png;Resources',
			 '--add-binary',
			 'Resources/Underline.png;Resources'

pyinstaller $arguments 2>&1 > .\pyinstaller-build.log
