pyside6-rcc postnote.qrc -o postnote_rc.py
pyside6-uic postnote.ui -o ui_postnote.py
pyside6-uic note_wnd.ui -o ui_note_wnd.py
pyside6-uic button_bar_widget.ui -o ui_button_bar_widget.py
pyside6-uic edit_toolbar.ui -o ui_edit_toolbar.py
pyside6-uic edit_topics_dialog.ui -o ui_edit_topics_dialog.py
pyside6-uic edit_topic_attr_dlg.ui -o ui_edit_topic_addr_dlg.py
pyside6-uic preferences_dlg.ui -o ui_preferences_dlg.py
pyside6-uic note_properties_dlg.ui -o ui_note_properties_dlg.py
pyside6-uic edit_note_color_scheme_dlg.ui -o ui_edit_note_color_scheme_dlg.py
pyside6-uic quick_create_dlg.ui -o ui_quick_create_dlg.py
pyside6-uic about_dlg.ui -o ui_about_dlg.py
pyside6-uic style_dlg.ui -o ui_style_dlg.py
pyside6-uic select_style_dlg.ui -o ui_select_style_dlg.py